// Barrel exports for Authentication ORM functions

// Authentication Models - export all from authOrm except User functions
export {
  aggregateAccountsOrm,
  aggregateApiKeysOrm,
  aggregateAuditLogsOrm,
  aggregateBackupCodesOrm,
  aggregateInvitationsOrm,
  aggregateMembersOrm,
  aggregateOrganizationsOrm,
  aggregatePasskeysOrm,
  aggregateSessionsOrm,
  aggregateTeamMembersOrm,
  aggregateTeamsOrm,
  aggregateTwoFactorsOrm,
  aggregateVerificationsOrm,
  countAccountsOrm,
  countApiKeysOrm,
  countAuditLogsOrm,
  countBackupCodesOrm,
  countInvitationsOrm,
  countMembersOrm,
  countOrganizationsOrm,
  countPasskeysOrm,
  countSessionsOrm,
  countTeamMembersOrm,
  countTeamsOrm,
  countTwoFactorsOrm,
  countVerificationsOrm,
  // Account operations
  createAccountOrm,
  // ApiKey operations
  createApiKeyOrm,
  // AuditLog operations
  createAuditLogOrm,
  // BackupCode operations
  createBackupCodeOrm,
  // Invitation operations
  createInvitationOrm,
  // Member operations
  createMemberOrm,
  // Organization operations
  createOrganizationOrm,
  // Passkey operations
  createPasskeyOrm,
  // Session operations
  createSessionOrm,
  // TeamMember operations
  createTeamMemberOrm,
  // Team operations
  createTeamOrm,
  // TwoFactor operations
  createTwoFactorOrm,
  createUserWithOrganizationOrm,
  // Verification operations
  createVerificationOrm,
  deleteAccountOrm,
  deleteApiKeyOrm,
  deleteAuditLogOrm,
  deleteBackupCodeOrm,
  deleteInvitationOrm,
  deleteManyAccountsOrm,
  deleteManyApiKeysOrm,
  deleteManyAuditLogsOrm,
  deleteManyBackupCodesOrm,
  deleteManyInvitationsOrm,
  deleteManyMembersOrm,
  deleteManyOrganizationsOrm,
  deleteManyPasskeysOrm,
  deleteManySessionsOrm,
  deleteManyTeamMembersOrm,
  deleteManyTeamsOrm,
  deleteManyTwoFactorsOrm,
  deleteManyVerificationsOrm,
  deleteMemberOrm,
  deleteOrganizationOrm,
  deletePasskeyOrm,
  deleteSessionOrm,
  deleteTeamMemberOrm,
  deleteTeamOrm,
  deleteTwoFactorOrm,
  deleteVerificationOrm,
  findFirstAccountOrm,
  findFirstApiKeyOrm,
  findFirstAuditLogOrm,
  findFirstBackupCodeOrm,
  findFirstInvitationOrm,
  findFirstMemberOrm,
  findFirstOrganizationOrm,
  findFirstPasskeyOrm,
  findFirstSessionOrm,
  findFirstTeamMemberOrm,
  findFirstTeamOrm,
  findFirstTwoFactorOrm,
  findFirstVerificationOrm,
  findManyAccountsOrm,
  findManyApiKeysOrm,
  findManyAuditLogsOrm,
  findManyBackupCodesOrm,
  findManyInvitationsOrm,
  findManyMembersOrm,
  findManyOrganizationsOrm,
  findManyPasskeysOrm,
  findManySessionsOrm,
  findManyTeamMembersOrm,
  findManyTeamsOrm,
  findManyTwoFactorsOrm,
  findManyVerificationsOrm,
  findOrganizationWithMembersOrm,
  findUniqueAccountOrm,
  findUniqueApiKeyOrm,
  findUniqueAuditLogOrm,
  findUniqueBackupCodeOrm,
  findUniqueInvitationOrm,
  findUniqueMemberOrm,
  findUniqueOrganizationOrm,
  findUniquePasskeyOrm,
  findUniqueSessionOrm,
  findUniqueTeamMemberOrm,
  findUniqueTeamOrm,
  findUniqueTwoFactorOrm,
  findUniqueVerificationOrm,
  // Specialized functions
  findUserWithAuthContextOrm,
  groupByAccountsOrm,
  groupByApiKeysOrm,
  groupByAuditLogsOrm,
  groupByBackupCodesOrm,
  groupByInvitationsOrm,
  groupByMembersOrm,
  groupByOrganizationsOrm,
  groupByPasskeysOrm,
  groupBySessionsOrm,
  groupByTeamMembersOrm,
  groupByTeamsOrm,
  groupByTwoFactorsOrm,
  groupByVerificationsOrm,
  updateAccountOrm,
  updateApiKeyOrm,
  updateAuditLogOrm,
  updateBackupCodeOrm,
  updateInvitationOrm,
  updateManyAccountsOrm,
  updateManyApiKeysOrm,
  updateManyAuditLogsOrm,
  updateManyBackupCodesOrm,
  updateManyInvitationsOrm,
  updateManyMembersOrm,
  updateManyOrganizationsOrm,
  updateManyPasskeysOrm,
  updateManySessionsOrm,
  updateManyTeamMembersOrm,
  updateManyTeamsOrm,
  updateManyTwoFactorsOrm,
  updateManyVerificationsOrm,
  updateMemberOrm,
  updateOrganizationOrm,
  updatePasskeyOrm,
  updateSessionOrm,
  updateTeamMemberOrm,
  updateTeamOrm,
  updateTwoFactorOrm,
  updateVerificationOrm,
  upsertAccountOrm,
  upsertApiKeyOrm,
  upsertAuditLogOrm,
  upsertBackupCodeOrm,
  upsertInvitationOrm,
  upsertMemberOrm,
  upsertOrganizationOrm,
  upsertPasskeyOrm,
  upsertSessionOrm,
  upsertTeamMemberOrm,
  upsertTeamOrm,
  upsertTwoFactorOrm,
  upsertVerificationOrm,
} from './authOrm';

// User-specific operations from userOrm
export {
  aggregateUsersOrm,
  countUsersOrm,
  // User CRUD operations
  createUserOrm,
  deleteManyUsersOrm,
  deleteUserOrm,
  findFirstUserOrm,
  findManyUsersOrm,
  findUniqueUserOrm,
  findUniqueUserOrmOrThrow,
  findUserWithAllRelationsOrm,
  // Specialized User functions
  findUserWithProfileOrm,
  groupByUsersOrm,
  updateManyUsersOrm,
  updateUserOrm,
  upsertUserOrm,
} from './userOrm';

// Type exports
export type { OrganizationWithMembers, UserWithAuthContext } from './authOrm';

export type { UserWithAllRelations, UserWithBasicRelations } from './userOrm';
