export default {
  index: 'Overview',
  ai: 'AI',
  analytics: 'Analytics',
  auth: 'Authentication',
  collaboration: 'Collaboration',
  config: 'Config',
  'config-eslint': 'ESLint Config',
  database: 'Database',
  'design-system': 'Design System',
  email: 'Email',
  'feature-flags': 'Feature Flags (Deprecated)',
  internationalization: 'Internationalization',
  'next-config': 'Next.js Config',
  notifications: 'Notifications',
  observability: 'Observability',
  orchestration: 'Orchestration',
  payments: 'Payments',
  'rate-limit': 'Rate Limit',
  scraping: 'Scraping',
  security: 'Security',
  seo: 'SEO',
  storage: 'Storage',
  testing: 'Testing',
  'typescript-config': 'TypeScript Config',
  webhooks: 'Webhooks',
};
