packages:
  - apps/*
  - functions/*
  - infrastructure/*
  - packages/*

catalog:
  '@hookform/resolvers': ^5.1.1
  '@hugeicons/core-free-icons': ^1.0.14
  '@hugeicons/react': ^1.0.5
  '@mantine/carousel': ^8.1.3
  '@mantine/charts': ^8.1.3
  '@mantine/code-highlight': ^8.1.3
  '@mantine/core': ^8.1.3
  '@mantine/dates': ^8.1.3
  '@mantine/dropzone': ^8.1.3
  '@mantine/form': ^8.1.3
  '@mantine/hooks': ^8.1.3
  '@mantine/modals': ^8.1.3
  '@mantine/notifications': ^8.1.3
  '@mantine/nprogress': ^8.1.3
  '@sentry/nextjs': ^9.38.0
  '@t3-oss/env-nextjs': ^0.13.8
  '@tabler/icons-react': ^3.34.0
  '@tailwindcss/postcss': ^4.1.11
  '@testing-library/dom': ^10.4.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  '@types/node': ^24.0.14
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react': ^4.6.0
  '@vitest/coverage-v8': ^3.2.4
  clsx: ^2.1.1
  date-fns: ^4.1.0
  eslint: ^9.31.0
  jsdom: ^26.1.0
  knip: ^5.61.3
  madge: ^8.0.0
  mantine-form-zod-resolver: ^1.3.0
  nanoid: ^5.1.5
  next: 15.4.2-canary.0
  postcss: ^8.5.6
  postcss-preset-mantine: ^1.18.0
  postcss-simple-vars: ^7.0.1
  react: ^19.1.0
  react-dom: ^19.1.0
  recharts: ^3.1.0
  tailwind-preset-mantine: ^2.1.0
  tailwindcss: ^4.1.11
  typescript: ^5.8.3
  vite: ^7.0.4
  vitest: ^3.2.4
  zod: ^4.0.5
