packages:
  - apps/*
  - functions/*
  - infrastructure/*
  - packages/*
  - packages/pkgs-databases/*
  - packages/pkgs-integrations/*
  - labs/*

catalog:
  # AI Platform
  '@ai-sdk/gateway': ^1.0.15
  '@ai-sdk/provider': ^2.0.0
  '@ai-sdk/provider-utils': ^3.0.7
  '@ai-sdk/react': ^2.0.60
  '@ai-sdk/xai': ^2.0.14
  ai: ^5.0.34
  # UI & Styling
  '@mantine/carousel': ^8.2.2
  '@mantine/code-highlight': ^8.2.2
  '@mantine/core': ^8.2.2
  '@mantine/dates': ^8.2.2
  '@mantine/dropzone': ^8.2.2
  '@mantine/form': ^8.2.2
  '@mantine/hooks': ^8.2.2
  '@mantine/modals': ^8.2.2
  '@mantine/notifications': ^8.2.2
  '@tabler/icons-react': ^3.34.1
  '@tailwindcss/postcss': ^4.1.11
  clsx: ^2.1.1
  cmdk: ^1.0.4
  react: ^19.1.0
  react-dom: ^19.1.0
  react-markdown: ^9.0.1
  tailwind-preset-mantine: ^2.1.0
  tailwindcss: ^4.1.11
  # Forms & UX Utilities
  '@hookform/resolvers': ^5.2.0
  date-fns: ^4.1.0
  lru-cache: ^11.0.2
  nanoid: ^5.1.5
  recharts: ^3.1.0
  # Application Runtime & Hosting
  '@sentry/nextjs': ^9.44.2
  '@t3-oss/env-nextjs': ^0.13.8
  '@vercel/kv': ^1.0.1
  next: ^15.5.0
  # Testing & QA
  '@playwright/test': ^1.49.1
  '@testing-library/jest-dom': ^6.8.0
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  jest-axe: ^10.0.0
  jsdom: ^26.1.0
  vitest: ^3.2.4
  # Type Safety & Schema
  '@types/node': ^24.1.0
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.9
  ts-pattern: ^5.0.8
  typescript: ^5.9.2
  zod: ^4.1.5
  # Build & Tooling
  '@next/eslint-plugin-next': ^15.5.0
  '@vitejs/plugin-react': ^5.0.2
  eslint: ^9.34.0
  knip: ^5.63.0
  madge: ^8.0.0
  postcss: ^8.5.6
  vite: ^7.0.6
  vite-tsconfig-paths: ^5.1.4

catalogs:
  downgrades:
    zod: 3.25.76

engineStrict: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@sentry/cli'
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - oxc-resolver
  - prisma
  - prisma-zod-generator
  - puppeteer
  - sharp

requiredScripts:
  - build
  - test

useNodeVersion: 22.15.1
