packages:
  - apps/*
  - functions/*
  - infrastructure/*
  - packages/*
  - labs/*

catalog:
  '@ai-sdk/anthropic': 2.0.0-canary.19
  '@ai-sdk/deepinfra': ^1.0.0-beta.30
  '@ai-sdk/google': ^2.0.0-beta.30
  '@ai-sdk/openai': ^2.0.0-beta.30
  '@ai-sdk/openai-compatible': ^1.0.0-beta.30
  '@ai-sdk/perplexity': ^2.0.0-beta.30
  '@ai-sdk/provider': ^2.0.0-beta.30
  '@ai-sdk/provider-utils': ^3.0.0-beta.30
  '@ai-sdk/react': ^2.0.0-beta.30
  '@ai-sdk/rsc': ^1.0.0-canary.22
  '@ai-sdk/xai': ^2.0.0-beta.30
  '@headlessui/react': ^2.2.6
  '@heroicons/react': ^2.2.0
  '@hookform/resolvers': ^5.2.0
  '@hugeicons/core-free-icons': ^1.0.16
  '@hugeicons/react': ^1.0.5
  '@mantine/carousel': ^8.2.1
  '@mantine/charts': ^8.2.1
  '@mantine/code-highlight': ^8.2.1
  '@mantine/core': ^8.2.1
  '@mantine/dates': ^8.2.1
  '@mantine/dropzone': ^8.2.1
  '@mantine/form': ^8.2.1
  '@mantine/hooks': 8.2.1
  '@mantine/modals': ^8.2.1
  '@mantine/notifications': ^8.2.1
  '@mantine/nprogress': ^8.2.1
  '@playwright/test': ^1.49.1
  '@sentry/nextjs': ^9.42.0
  '@t3-oss/env-nextjs': ^0.13.8
  '@tabler/icons-react': ^3.34.1
  '@tailwindcss/aspect-ratio': ^0.4.2
  '@tailwindcss/postcss': ^4.1.11
  '@tailwindcss/typography': ^0.5.16
  '@testing-library/dom': ^10.4.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  '@types/node': ^24.1.0
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react': ^4.7.0
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  ai: ^5.0.0-beta.30
  clsx: ^2.1.1
  date-fns: ^4.1.0
  embla-carousel: ^8.6.0
  embla-carousel-autoplay: ^8.6.0
  embla-carousel-react: ^8.6.0
  eslint: ^9.32.0
  jsdom: ^26.1.0
  knip: ^5.62.0
  madge: ^8.0.0
  mantine-form-zod-resolver: ^1.3.0
  nanoid: ^5.1.5
  next: ^15.4.4
  postcss: ^8.5.6
  postcss-preset-mantine: ^1.18.0
  postcss-simple-vars: ^7.0.1
  rc-slider: ^11.1.8
  react: ^19.1.0
  react-dom: ^19.1.0
  react-hot-toast: ^2.5.2
  react-swipeable: ^7.0.2
  react-use: ^17.6.0
  recharts: ^3.1.0
  sass: ^1.89.2
  tailwind-preset-mantine: ^2.1.0
  tailwindcss: ^4.1.11
  typescript: ^5.8.3
  vite: ^7.0.6
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  zod: ^4.0.10
