
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.9.0
 * Query Engine version: 81e4af48011447c3cc503a190e86995b66d2a28e
 */
Prisma.prismaVersion = {
  client: "6.9.0",
  engine: "81e4af48011447c3cc503a190e86995b66d2a28e"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  phoneNumber: 'phoneNumber',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  role: 'role',
  banned: 'banned',
  banReason: 'banReason',
  banExpires: 'banExpires',
  deletedAt: 'deletedAt',
  bio: 'bio',
  expertise: 'expertise',
  isVerifiedAuthor: 'isVerifiedAuthor',
  authorSince: 'authorSince',
  preferences: 'preferences',
  isSuspended: 'isSuspended',
  suspensionDetails: 'suspensionDetails'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  expiresAt: 'expiresAt',
  token: 'token',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  userId: 'userId',
  activeOrganizationId: 'activeOrganizationId',
  impersonatedBy: 'impersonatedBy'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrganizationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  logo: 'logo',
  description: 'description',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MemberScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  organizationId: 'organizationId',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  organizationId: 'organizationId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamMemberScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  teamId: 'teamId',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvitationScalarFieldEnum = {
  id: 'id',
  email: 'email',
  invitedById: 'invitedById',
  organizationId: 'organizationId',
  role: 'role',
  teamId: 'teamId',
  status: 'status',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ApiKeyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  start: 'start',
  prefix: 'prefix',
  key: 'key',
  keyHash: 'keyHash',
  userId: 'userId',
  organizationId: 'organizationId',
  refillInterval: 'refillInterval',
  refillAmount: 'refillAmount',
  lastRefillAt: 'lastRefillAt',
  lastUsedAt: 'lastUsedAt',
  enabled: 'enabled',
  rateLimitEnabled: 'rateLimitEnabled',
  rateLimitTimeWindow: 'rateLimitTimeWindow',
  rateLimitMax: 'rateLimitMax',
  requestCount: 'requestCount',
  remaining: 'remaining',
  lastRequest: 'lastRequest',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  permissions: 'permissions',
  metadata: 'metadata'
};

exports.Prisma.TwoFactorScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  secret: 'secret',
  secretHash: 'secretHash',
  enabled: 'enabled',
  verified: 'verified',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BackupCodeScalarFieldEnum = {
  id: 'id',
  code: 'code',
  codeHash: 'codeHash',
  userId: 'userId',
  twoFactorId: 'twoFactorId',
  used: 'used',
  usedAt: 'usedAt',
  createdAt: 'createdAt'
};

exports.Prisma.PasskeyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  userId: 'userId',
  credentialId: 'credentialId',
  publicKey: 'publicKey',
  counter: 'counter',
  deviceType: 'deviceType',
  backedUp: 'backedUp',
  transports: 'transports',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastUsedAt: 'lastUsedAt'
};

exports.Prisma.ProductCategoryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  name: 'name',
  slug: 'slug',
  status: 'status',
  description: 'description',
  copy: 'copy',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription',
  metaKeywords: 'metaKeywords',
  parentId: 'parentId',
  displayOrder: 'displayOrder'
};

exports.Prisma.ArticleScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  title: 'title',
  slug: 'slug',
  content: 'content',
  status: 'status',
  userId: 'userId'
};

exports.Prisma.BrandScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  name: 'name',
  slug: 'slug',
  type: 'type',
  status: 'status',
  copy: 'copy',
  baseUrl: 'baseUrl',
  parentId: 'parentId',
  displayOrder: 'displayOrder'
};

exports.Prisma.CollectionScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  name: 'name',
  slug: 'slug',
  type: 'type',
  status: 'status',
  copy: 'copy',
  userId: 'userId',
  parentId: 'parentId'
};

exports.Prisma.TaxonomyScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  name: 'name',
  slug: 'slug',
  type: 'type',
  status: 'status',
  copy: 'copy'
};

exports.Prisma.ReviewScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  title: 'title',
  content: 'content',
  rating: 'rating',
  status: 'status',
  verified: 'verified',
  type: 'type',
  sourceId: 'sourceId',
  source: 'source',
  helpfulCount: 'helpfulCount',
  totalVotes: 'totalVotes',
  userId: 'userId',
  productId: 'productId'
};

exports.Prisma.RegistryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  title: 'title',
  description: 'description',
  type: 'type',
  isPublic: 'isPublic',
  eventDate: 'eventDate',
  createdByUserId: 'createdByUserId'
};

exports.Prisma.RegistryItemScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  quantity: 'quantity',
  priority: 'priority',
  notes: 'notes',
  purchased: 'purchased',
  registryId: 'registryId',
  productId: 'productId',
  collectionId: 'collectionId'
};

exports.Prisma.RegistryPurchaseJoinScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  purchaseDate: 'purchaseDate',
  quantity: 'quantity',
  status: 'status',
  transactionId: 'transactionId',
  orderNumber: 'orderNumber',
  price: 'price',
  currency: 'currency',
  trackingNumber: 'trackingNumber',
  trackingUrl: 'trackingUrl',
  estimatedDelivery: 'estimatedDelivery',
  actualDelivery: 'actualDelivery',
  isGift: 'isGift',
  giftMessage: 'giftMessage',
  giftWrapped: 'giftWrapped',
  thankYouSent: 'thankYouSent',
  thankYouSentAt: 'thankYouSentAt',
  thankYouMessage: 'thankYouMessage',
  notes: 'notes',
  purchaserId: 'purchaserId',
  registryItemId: 'registryItemId',
  notifiedOwner: 'notifiedOwner',
  notifiedDate: 'notifiedDate'
};

exports.Prisma.MediaScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  url: 'url',
  altText: 'altText',
  type: 'type',
  width: 'width',
  height: 'height',
  size: 'size',
  mimeType: 'mimeType',
  userId: 'userId',
  articleId: 'articleId',
  brandId: 'brandId',
  collectionId: 'collectionId',
  productId: 'productId',
  taxonomyId: 'taxonomyId',
  reviewId: 'reviewId',
  categoryId: 'categoryId'
};

exports.Prisma.PdpJoinScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  productId: 'productId',
  brandId: 'brandId'
};

exports.Prisma.FavoriteJoinScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  productId: 'productId',
  collectionId: 'collectionId'
};

exports.Prisma.ReviewVoteJoinScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  voteType: 'voteType',
  userId: 'userId',
  reviewId: 'reviewId'
};

exports.Prisma.RegistryUserJoinScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  role: 'role',
  userId: 'userId',
  registryId: 'registryId'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  sku: 'sku',
  description: 'description',
  category: 'category',
  status: 'status',
  brand: 'brand',
  price: 'price',
  currency: 'currency',
  type: 'type',
  copy: 'copy',
  canonicalUrl: 'canonicalUrl',
  parentId: 'parentId',
  attributes: 'attributes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdBy: 'createdBy',
  organizationId: 'organizationId',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  aiGenerated: 'aiGenerated',
  aiConfidence: 'aiConfidence',
  aiSources: 'aiSources'
};

exports.Prisma.ProductBarcodeScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  barcode: 'barcode',
  type: 'type',
  isPrimary: 'isPrimary',
  createdAt: 'createdAt'
};

exports.Prisma.ProductAssetScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  type: 'type',
  url: 'url',
  filename: 'filename',
  mimeType: 'mimeType',
  size: 'size',
  alt: 'alt',
  description: 'description',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ScanHistoryScalarFieldEnum = {
  id: 'id',
  barcode: 'barcode',
  type: 'type',
  productId: 'productId',
  userId: 'userId',
  sessionId: 'sessionId',
  platform: 'platform',
  userAgent: 'userAgent',
  ipAddress: 'ipAddress',
  success: 'success',
  scannedAt: 'scannedAt',
  rawData: 'rawData',
  note: 'note',
  createdAt: 'createdAt'
};

exports.Prisma.WorkflowConfigScalarFieldEnum = {
  id: 'id',
  workflowSlug: 'workflowSlug',
  organizationId: 'organizationId',
  userId: 'userId',
  isEnabled: 'isEnabled',
  displayName: 'displayName',
  description: 'description',
  category: 'category',
  tags: 'tags',
  notifyOnStart: 'notifyOnStart',
  notifyOnComplete: 'notifyOnComplete',
  notifyOnFailure: 'notifyOnFailure',
  notifyOnApproval: 'notifyOnApproval',
  notificationEmail: 'notificationEmail',
  maxRetries: 'maxRetries',
  timeoutSeconds: 'timeoutSeconds',
  rateLimitPerHour: 'rateLimitPerHour',
  maxConcurrent: 'maxConcurrent',
  priority: 'priority',
  customPayload: 'customPayload',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdBy: 'createdBy'
};

exports.Prisma.WorkflowExecutionScalarFieldEnum = {
  id: 'id',
  workflowRunId: 'workflowRunId',
  workflowSlug: 'workflowSlug',
  userId: 'userId',
  organizationId: 'organizationId',
  status: 'status',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  duration: 'duration',
  inputPayloadHash: 'inputPayloadHash',
  hasOutput: 'hasOutput',
  error: 'error',
  errorType: 'errorType',
  stepCount: 'stepCount',
  completedSteps: 'completedSteps',
  retryCount: 'retryCount',
  triggeredBy: 'triggeredBy',
  triggerSource: 'triggerSource',
  parentExecutionId: 'parentExecutionId',
  creditsUsed: 'creditsUsed',
  apiCallCount: 'apiCallCount',
  tags: 'tags',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkflowScheduleScalarFieldEnum = {
  id: 'id',
  configId: 'configId',
  name: 'name',
  description: 'description',
  cronExpression: 'cronExpression',
  timezone: 'timezone',
  isActive: 'isActive',
  payload: 'payload',
  nextRunAt: 'nextRunAt',
  lastRunAt: 'lastRunAt',
  lastRunStatus: 'lastRunStatus',
  totalRuns: 'totalRuns',
  successfulRuns: 'successfulRuns',
  failedRuns: 'failedRuns',
  validFrom: 'validFrom',
  validUntil: 'validUntil',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdBy: 'createdBy'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.ContentStatus = exports.$Enums.ContentStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED'
};

exports.BrandType = exports.$Enums.BrandType = {
  MANUFACTURER: 'MANUFACTURER',
  RETAILER: 'RETAILER',
  MARKETPLACE: 'MARKETPLACE',
  SERVICE: 'SERVICE',
  OTHER: 'OTHER'
};

exports.CollectionType = exports.$Enums.CollectionType = {
  SEASONAL: 'SEASONAL',
  THEMATIC: 'THEMATIC',
  PRODUCT_LINE: 'PRODUCT_LINE',
  BRAND_LINE: 'BRAND_LINE',
  PROMOTIONAL: 'PROMOTIONAL',
  CURATED: 'CURATED',
  TRENDING: 'TRENDING',
  FEATURED: 'FEATURED',
  NEW_ARRIVALS: 'NEW_ARRIVALS',
  BEST_SELLERS: 'BEST_SELLERS',
  CLEARANCE: 'CLEARANCE',
  LIMITED_EDITION: 'LIMITED_EDITION',
  COLLABORATION: 'COLLABORATION',
  EXCLUSIVE: 'EXCLUSIVE',
  BUNDLE: 'BUNDLE',
  SET: 'SET',
  OTHER: 'OTHER'
};

exports.TaxonomyType = exports.$Enums.TaxonomyType = {
  CATEGORY: 'CATEGORY',
  TAG: 'TAG',
  ATTRIBUTE: 'ATTRIBUTE',
  DEPARTMENT: 'DEPARTMENT',
  COLLECTION: 'COLLECTION',
  OTHER: 'OTHER'
};

exports.ReviewType = exports.$Enums.ReviewType = {
  IMPORTED: 'IMPORTED',
  DEDICATED: 'DEDICATED'
};

exports.RegistryType = exports.$Enums.RegistryType = {
  WISHLIST: 'WISHLIST',
  GIFT: 'GIFT',
  WEDDING: 'WEDDING',
  BABY: 'BABY',
  BIRTHDAY: 'BIRTHDAY',
  HOLIDAY: 'HOLIDAY',
  OTHER: 'OTHER'
};

exports.PurchaseStatus = exports.$Enums.PurchaseStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  RETURNED: 'RETURNED'
};

exports.MediaType = exports.$Enums.MediaType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
  AUDIO: 'AUDIO'
};

exports.VoteType = exports.$Enums.VoteType = {
  HELPFUL: 'HELPFUL',
  NOT_HELPFUL: 'NOT_HELPFUL'
};

exports.RegistryUserRole = exports.$Enums.RegistryUserRole = {
  OWNER: 'OWNER',
  EDITOR: 'EDITOR',
  VIEWER: 'VIEWER'
};

exports.ProductStatus = exports.$Enums.ProductStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  DISCONTINUED: 'DISCONTINUED'
};

exports.ProductType = exports.$Enums.ProductType = {
  PHYSICAL: 'PHYSICAL',
  DIGITAL: 'DIGITAL',
  SERVICE: 'SERVICE',
  SUBSCRIPTION: 'SUBSCRIPTION',
  BUNDLE: 'BUNDLE',
  VARIANT: 'VARIANT',
  OTHER: 'OTHER'
};

exports.BarcodeType = exports.$Enums.BarcodeType = {
  UPC_A: 'UPC_A',
  UPC_E: 'UPC_E',
  EAN_13: 'EAN_13',
  EAN_8: 'EAN_8',
  CODE_128: 'CODE_128',
  CODE_39: 'CODE_39',
  QR_CODE: 'QR_CODE',
  PDF417: 'PDF417',
  AZTEC: 'AZTEC',
  DATA_MATRIX: 'DATA_MATRIX',
  ITF14: 'ITF14',
  CODABAR: 'CODABAR',
  OTHER: 'OTHER'
};

exports.AssetType = exports.$Enums.AssetType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
  MANUAL: 'MANUAL',
  SPECIFICATION: 'SPECIFICATION',
  CERTIFICATE: 'CERTIFICATE',
  OTHER: 'OTHER'
};

exports.Prisma.ModelName = {
  User: 'User',
  Session: 'Session',
  Account: 'Account',
  Verification: 'Verification',
  Organization: 'Organization',
  Member: 'Member',
  Team: 'Team',
  TeamMember: 'TeamMember',
  Invitation: 'Invitation',
  ApiKey: 'ApiKey',
  TwoFactor: 'TwoFactor',
  BackupCode: 'BackupCode',
  Passkey: 'Passkey',
  ProductCategory: 'ProductCategory',
  Article: 'Article',
  Brand: 'Brand',
  Collection: 'Collection',
  Taxonomy: 'Taxonomy',
  Review: 'Review',
  Registry: 'Registry',
  RegistryItem: 'RegistryItem',
  RegistryPurchaseJoin: 'RegistryPurchaseJoin',
  Media: 'Media',
  PdpJoin: 'PdpJoin',
  FavoriteJoin: 'FavoriteJoin',
  ReviewVoteJoin: 'ReviewVoteJoin',
  RegistryUserJoin: 'RegistryUserJoin',
  Product: 'Product',
  ProductBarcode: 'ProductBarcode',
  ProductAsset: 'ProductAsset',
  ScanHistory: 'ScanHistory',
  WorkflowConfig: 'WorkflowConfig',
  WorkflowExecution: 'WorkflowExecution',
  WorkflowSchedule: 'WorkflowSchedule'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
