
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.10.1
 * Query Engine version: 9b628578b3b7cae625e8c927178f15a170e74a9c
 */
Prisma.prismaVersion = {
  client: "6.10.1",
  engine: "9b628578b3b7cae625e8c927178f15a170e74a9c"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  phoneNumber: 'phoneNumber',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  role: 'role',
  banned: 'banned',
  banReason: 'banReason',
  banExpires: 'banExpires',
  deletedAt: 'deletedAt',
  bio: 'bio',
  expertise: 'expertise',
  isVerifiedAuthor: 'isVerifiedAuthor',
  authorSince: 'authorSince',
  preferences: 'preferences',
  isSuspended: 'isSuspended',
  suspensionDetails: 'suspensionDetails'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  expiresAt: 'expiresAt',
  token: 'token',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  userId: 'userId',
  activeOrganizationId: 'activeOrganizationId',
  impersonatedBy: 'impersonatedBy'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrganizationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  logo: 'logo',
  description: 'description',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MemberScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  organizationId: 'organizationId',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  organizationId: 'organizationId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamMemberScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  teamId: 'teamId',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvitationScalarFieldEnum = {
  id: 'id',
  email: 'email',
  invitedById: 'invitedById',
  organizationId: 'organizationId',
  role: 'role',
  teamId: 'teamId',
  status: 'status',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ApiKeyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  start: 'start',
  prefix: 'prefix',
  key: 'key',
  keyHash: 'keyHash',
  userId: 'userId',
  organizationId: 'organizationId',
  refillInterval: 'refillInterval',
  refillAmount: 'refillAmount',
  lastRefillAt: 'lastRefillAt',
  lastUsedAt: 'lastUsedAt',
  enabled: 'enabled',
  rateLimitEnabled: 'rateLimitEnabled',
  rateLimitTimeWindow: 'rateLimitTimeWindow',
  rateLimitMax: 'rateLimitMax',
  requestCount: 'requestCount',
  remaining: 'remaining',
  lastRequest: 'lastRequest',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  permissions: 'permissions',
  metadata: 'metadata'
};

exports.Prisma.TwoFactorScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  secret: 'secret',
  secretHash: 'secretHash',
  enabled: 'enabled',
  verified: 'verified',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BackupCodeScalarFieldEnum = {
  id: 'id',
  code: 'code',
  codeHash: 'codeHash',
  userId: 'userId',
  twoFactorId: 'twoFactorId',
  used: 'used',
  usedAt: 'usedAt',
  createdAt: 'createdAt'
};

exports.Prisma.PasskeyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  userId: 'userId',
  credentialId: 'credentialId',
  publicKey: 'publicKey',
  counter: 'counter',
  deviceType: 'deviceType',
  backedUp: 'backedUp',
  transports: 'transports',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastUsedAt: 'lastUsedAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  type: 'type',
  action: 'action',
  userId: 'userId',
  email: 'email',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  metadata: 'metadata',
  success: 'success',
  errorMessage: 'errorMessage',
  timestamp: 'timestamp'
};

exports.Prisma.ArticleScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  title: 'title',
  slug: 'slug',
  content: 'content',
  status: 'status',
  userId: 'userId'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  sku: 'sku',
  category: 'category',
  status: 'status',
  brand: 'brand',
  price: 'price',
  currency: 'currency',
  type: 'type',
  variantPrice: 'variantPrice',
  compareAtPrice: 'compareAtPrice',
  physicalProperties: 'physicalProperties',
  displayOrder: 'displayOrder',
  isDefault: 'isDefault',
  copy: 'copy',
  attributes: 'attributes',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdBy: 'createdBy',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  aiGenerated: 'aiGenerated',
  aiConfidence: 'aiConfidence',
  aiSources: 'aiSources'
};

exports.Prisma.PdpJoinScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  brandId: 'brandId',
  canonicalUrl: 'canonicalUrl',
  iframeUrl: 'iframeUrl',
  tempMediaUrls: 'tempMediaUrls',
  lastScanned: 'lastScanned',
  copy: 'copy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PdpUrlScalarFieldEnum = {
  id: 'id',
  name: 'name',
  url: 'url',
  pdpJoinId: 'pdpJoinId',
  urlType: 'urlType',
  isActive: 'isActive',
  copy: 'copy',
  createdAt: 'createdAt'
};

exports.Prisma.ProductIdentifiersScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  pdpJoinId: 'pdpJoinId',
  collectionId: 'collectionId',
  brandId: 'brandId',
  mpn: 'mpn',
  upcA: 'upcA',
  ean13: 'ean13',
  gs1128: 'gs1128',
  upcE: 'upcE',
  ean8: 'ean8',
  isbn10: 'isbn10',
  isbn13: 'isbn13',
  asin: 'asin',
  tcin: 'tcin',
  dpci: 'dpci',
  themoviedbId: 'themoviedbId',
  hardcoverappId: 'hardcoverappId',
  itf14: 'itf14',
  customBarcode: 'customBarcode',
  customBarcodeType: 'customBarcodeType',
  primaryIdentifierField: 'primaryIdentifierField',
  source: 'source',
  verifiedAt: 'verifiedAt',
  confidence: 'confidence',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BrandScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  type: 'type',
  status: 'status',
  baseUrl: 'baseUrl',
  copy: 'copy',
  parentId: 'parentId',
  displayOrder: 'displayOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById'
};

exports.Prisma.CastScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  isFictional: 'isFictional',
  copy: 'copy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById'
};

exports.Prisma.CollectionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  type: 'type',
  status: 'status',
  userId: 'userId',
  copy: 'copy',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById'
};

exports.Prisma.FandomScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  isFictional: 'isFictional',
  copy: 'copy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById'
};

exports.Prisma.LocationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  locationType: 'locationType',
  lodgingType: 'lodgingType',
  isFictional: 'isFictional',
  copy: 'copy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById'
};

exports.Prisma.MediaScalarFieldEnum = {
  id: 'id',
  url: 'url',
  altText: 'altText',
  type: 'type',
  width: 'width',
  height: 'height',
  size: 'size',
  mimeType: 'mimeType',
  sortOrder: 'sortOrder',
  userId: 'userId',
  copy: 'copy',
  articleId: 'articleId',
  brandId: 'brandId',
  collectionId: 'collectionId',
  productId: 'productId',
  taxonomyId: 'taxonomyId',
  categoryId: 'categoryId',
  pdpJoinId: 'pdpJoinId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  reviewId: 'reviewId'
};

exports.Prisma.ProductCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  status: 'status',
  copy: 'copy',
  parentId: 'parentId',
  displayOrder: 'displayOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById'
};

exports.Prisma.SeriesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  fandomId: 'fandomId',
  displayOrder: 'displayOrder',
  isFictional: 'isFictional',
  copy: 'copy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById'
};

exports.Prisma.StoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  seriesId: 'seriesId',
  fandomId: 'fandomId',
  displayOrder: 'displayOrder',
  isFictional: 'isFictional',
  copy: 'copy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById'
};

exports.Prisma.TaxonomyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  type: 'type',
  status: 'status',
  copy: 'copy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById'
};

exports.Prisma.JollyRogerScalarFieldEnum = {
  id: 'id',
  canChart: 'canChart',
  chartingMethod: 'chartingMethod',
  brandId: 'brandId',
  sitemaps: 'sitemaps',
  gridUrls: 'gridUrls',
  pdpUrlPatterns: 'pdpUrlPatterns'
};

exports.Prisma.JrExtractionRuleScalarFieldEnum = {
  id: 'id',
  jollyRogerId: 'jollyRogerId',
  fieldName: 'fieldName',
  isActive: 'isActive',
  selectors: 'selectors',
  mustContain: 'mustContain',
  cannotContain: 'cannotContain',
  lastSuccessfulSelector: 'lastSuccessfulSelector',
  successRate: 'successRate',
  lastTestedAt: 'lastTestedAt',
  notes: 'notes'
};

exports.Prisma.JrFindReplaceRejectScalarFieldEnum = {
  id: 'id',
  lookFor: 'lookFor',
  replaceWith: 'replaceWith',
  ruleAction: 'ruleAction',
  isRegex: 'isRegex',
  regexFlags: 'regexFlags',
  priority: 'priority'
};

exports.Prisma.ReviewScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  title: 'title',
  content: 'content',
  rating: 'rating',
  status: 'status',
  verified: 'verified',
  type: 'type',
  sourceId: 'sourceId',
  source: 'source',
  helpfulCount: 'helpfulCount',
  totalVotes: 'totalVotes',
  userId: 'userId',
  productId: 'productId'
};

exports.Prisma.FavoriteJoinScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  productId: 'productId',
  collectionId: 'collectionId'
};

exports.Prisma.ReviewVoteJoinScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  voteType: 'voteType',
  userId: 'userId',
  reviewId: 'reviewId'
};

exports.Prisma.AddressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  isDefault: 'isDefault',
  firstName: 'firstName',
  lastName: 'lastName',
  company: 'company',
  phone: 'phone',
  street1: 'street1',
  street2: 'street2',
  city: 'city',
  state: 'state',
  postalCode: 'postalCode',
  country: 'country',
  isValidated: 'isValidated',
  validatedAt: 'validatedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.CartScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  sessionId: 'sessionId',
  status: 'status',
  expiresAt: 'expiresAt',
  currency: 'currency',
  notes: 'notes',
  metadata: 'metadata',
  abandonedAt: 'abandonedAt',
  recoveredAt: 'recoveredAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.CartItemScalarFieldEnum = {
  id: 'id',
  cartId: 'cartId',
  productId: 'productId',
  variantId: 'variantId',
  quantity: 'quantity',
  price: 'price',
  isGift: 'isGift',
  giftMessage: 'giftMessage',
  registryId: 'registryId',
  savedForLater: 'savedForLater',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  orderNumber: 'orderNumber',
  userId: 'userId',
  guestEmail: 'guestEmail',
  guestName: 'guestName',
  status: 'status',
  shippingAddressId: 'shippingAddressId',
  billingAddressId: 'billingAddressId',
  currency: 'currency',
  subtotal: 'subtotal',
  taxAmount: 'taxAmount',
  shippingAmount: 'shippingAmount',
  discountAmount: 'discountAmount',
  total: 'total',
  shippingMethod: 'shippingMethod',
  trackingNumber: 'trackingNumber',
  shippedAt: 'shippedAt',
  deliveredAt: 'deliveredAt',
  paymentStatus: 'paymentStatus',
  paymentMethod: 'paymentMethod',
  customerNotes: 'customerNotes',
  internalNotes: 'internalNotes',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  variantId: 'variantId',
  productName: 'productName',
  variantName: 'variantName',
  sku: 'sku',
  quantity: 'quantity',
  price: 'price',
  total: 'total',
  isGift: 'isGift',
  giftMessage: 'giftMessage',
  registryId: 'registryId',
  status: 'status',
  fulfilledAt: 'fulfilledAt',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  type: 'type',
  status: 'status',
  amount: 'amount',
  currency: 'currency',
  gateway: 'gateway',
  gatewayId: 'gatewayId',
  gatewayResponse: 'gatewayResponse',
  paymentMethod: 'paymentMethod',
  last4: 'last4',
  parentTransactionId: 'parentTransactionId',
  metadata: 'metadata',
  processedAt: 'processedAt',
  failedAt: 'failedAt',
  failureReason: 'failureReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InventoryScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  variantId: 'variantId',
  quantity: 'quantity',
  reserved: 'reserved',
  available: 'available',
  lowStockThreshold: 'lowStockThreshold',
  locationId: 'locationId',
  locationName: 'locationName',
  lastRestockedAt: 'lastRestockedAt',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InventoryTransactionScalarFieldEnum = {
  id: 'id',
  inventoryId: 'inventoryId',
  type: 'type',
  quantity: 'quantity',
  referenceType: 'referenceType',
  referenceId: 'referenceId',
  notes: 'notes',
  createdAt: 'createdAt',
  createdBy: 'createdBy'
};

exports.Prisma.RegistryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  title: 'title',
  description: 'description',
  type: 'type',
  isPublic: 'isPublic',
  eventDate: 'eventDate',
  createdByUserId: 'createdByUserId'
};

exports.Prisma.RegistryItemScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  quantity: 'quantity',
  priority: 'priority',
  notes: 'notes',
  purchased: 'purchased',
  registryId: 'registryId',
  productId: 'productId',
  collectionId: 'collectionId'
};

exports.Prisma.RegistryPurchaseJoinScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  purchaseDate: 'purchaseDate',
  quantity: 'quantity',
  status: 'status',
  transactionId: 'transactionId',
  orderNumber: 'orderNumber',
  price: 'price',
  currency: 'currency',
  trackingNumber: 'trackingNumber',
  trackingUrl: 'trackingUrl',
  estimatedDelivery: 'estimatedDelivery',
  actualDelivery: 'actualDelivery',
  isGift: 'isGift',
  giftMessage: 'giftMessage',
  giftWrapped: 'giftWrapped',
  thankYouSent: 'thankYouSent',
  thankYouSentAt: 'thankYouSentAt',
  thankYouMessage: 'thankYouMessage',
  notes: 'notes',
  purchaserId: 'purchaserId',
  registryItemId: 'registryItemId',
  notifiedOwner: 'notifiedOwner',
  notifiedDate: 'notifiedDate'
};

exports.Prisma.RegistryUserJoinScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  role: 'role',
  userId: 'userId',
  registryId: 'registryId'
};

exports.Prisma.WorkflowConfigScalarFieldEnum = {
  id: 'id',
  workflowSlug: 'workflowSlug',
  organizationId: 'organizationId',
  userId: 'userId',
  isEnabled: 'isEnabled',
  displayName: 'displayName',
  description: 'description',
  category: 'category',
  tags: 'tags',
  notifyOnStart: 'notifyOnStart',
  notifyOnComplete: 'notifyOnComplete',
  notifyOnFailure: 'notifyOnFailure',
  notifyOnApproval: 'notifyOnApproval',
  notificationEmail: 'notificationEmail',
  maxRetries: 'maxRetries',
  timeoutSeconds: 'timeoutSeconds',
  rateLimitPerHour: 'rateLimitPerHour',
  maxConcurrent: 'maxConcurrent',
  priority: 'priority',
  customPayload: 'customPayload',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdBy: 'createdBy'
};

exports.Prisma.WorkflowExecutionScalarFieldEnum = {
  id: 'id',
  workflowRunId: 'workflowRunId',
  workflowSlug: 'workflowSlug',
  userId: 'userId',
  organizationId: 'organizationId',
  status: 'status',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  duration: 'duration',
  inputPayloadHash: 'inputPayloadHash',
  hasOutput: 'hasOutput',
  error: 'error',
  errorType: 'errorType',
  stepCount: 'stepCount',
  completedSteps: 'completedSteps',
  retryCount: 'retryCount',
  triggeredBy: 'triggeredBy',
  triggerSource: 'triggerSource',
  parentExecutionId: 'parentExecutionId',
  creditsUsed: 'creditsUsed',
  apiCallCount: 'apiCallCount',
  tags: 'tags',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkflowScheduleScalarFieldEnum = {
  id: 'id',
  configId: 'configId',
  name: 'name',
  description: 'description',
  cronExpression: 'cronExpression',
  timezone: 'timezone',
  isActive: 'isActive',
  payload: 'payload',
  nextRunAt: 'nextRunAt',
  lastRunAt: 'lastRunAt',
  lastRunStatus: 'lastRunStatus',
  totalRuns: 'totalRuns',
  successfulRuns: 'successfulRuns',
  failedRuns: 'failedRuns',
  validFrom: 'validFrom',
  validUntil: 'validUntil',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdBy: 'createdBy'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.ContentStatus = exports.$Enums.ContentStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED'
};

exports.ProductStatus = exports.$Enums.ProductStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  DISCONTINUED: 'DISCONTINUED'
};

exports.ProductType = exports.$Enums.ProductType = {
  PHYSICAL: 'PHYSICAL',
  DIGITAL: 'DIGITAL',
  SERVICE: 'SERVICE',
  SUBSCRIPTION: 'SUBSCRIPTION',
  BUNDLE: 'BUNDLE',
  VARIANT: 'VARIANT',
  OTHER: 'OTHER'
};

exports.PdpUrlType = exports.$Enums.PdpUrlType = {
  CANONICAL: 'CANONICAL',
  IFRAME: 'IFRAME',
  LEGACY: 'LEGACY',
  ALTERNATE: 'ALTERNATE'
};

exports.BrandType = exports.$Enums.BrandType = {
  LABEL: 'LABEL',
  RETAILER: 'RETAILER',
  MARKETPLACE: 'MARKETPLACE',
  OTHER: 'OTHER'
};

exports.CollectionType = exports.$Enums.CollectionType = {
  SEASONAL: 'SEASONAL',
  THEMATIC: 'THEMATIC',
  PRODUCT_LINE: 'PRODUCT_LINE',
  BRAND_LINE: 'BRAND_LINE',
  PROMOTIONAL: 'PROMOTIONAL',
  CURATED: 'CURATED',
  TRENDING: 'TRENDING',
  FEATURED: 'FEATURED',
  NEW_ARRIVALS: 'NEW_ARRIVALS',
  BEST_SELLERS: 'BEST_SELLERS',
  CLEARANCE: 'CLEARANCE',
  LIMITED_EDITION: 'LIMITED_EDITION',
  COLLABORATION: 'COLLABORATION',
  EXCLUSIVE: 'EXCLUSIVE',
  BUNDLE: 'BUNDLE',
  SET: 'SET',
  OTHER: 'OTHER'
};

exports.LocationType = exports.$Enums.LocationType = {
  DESTINATION: 'DESTINATION',
  LOCATION: 'LOCATION',
  LODGING: 'LODGING',
  PLACE: 'PLACE'
};

exports.LodgingType = exports.$Enums.LodgingType = {
  DISNEY_RESORT: 'DISNEY_RESORT',
  UNIVERSAL_RESORT: 'UNIVERSAL_RESORT',
  ONSITE_HOTEL: 'ONSITE_HOTEL',
  OFFSITE_HOTEL: 'OFFSITE_HOTEL',
  SHIP: 'SHIP',
  CAMPGROUND: 'CAMPGROUND',
  OTHER: 'OTHER'
};

exports.MediaType = exports.$Enums.MediaType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
  AUDIO: 'AUDIO',
  MANUAL: 'MANUAL',
  SPECIFICATION: 'SPECIFICATION',
  CERTIFICATE: 'CERTIFICATE'
};

exports.TaxonomyType = exports.$Enums.TaxonomyType = {
  TAG: 'TAG',
  ATTRACTION: 'ATTRACTION',
  THING: 'THING',
  COLOR: 'COLOR',
  MATERIAL: 'MATERIAL',
  EVENT: 'EVENT',
  ENTERTAINMENT: 'ENTERTAINMENT',
  OTHER: 'OTHER'
};

exports.JrChartMethod = exports.$Enums.JrChartMethod = {
  SITEMAP: 'SITEMAP',
  GRID: 'GRID'
};

exports.JrChartRuleFor = exports.$Enums.JrChartRuleFor = {
  AVAILABILITY: 'AVAILABILITY',
  BRAND: 'BRAND',
  CANONICAL_URL: 'CANONICAL_URL',
  DESCRIPTION: 'DESCRIPTION',
  DESCRIPTION_STRING: 'DESCRIPTION_STRING',
  JSON_LD: 'JSON_LD',
  MEDIA: 'MEDIA',
  NAME: 'NAME',
  OFFSITE_IFRAME: 'OFFSITE_IFRAME',
  PRICE: 'PRICE',
  SKU: 'SKU',
  SUMMARY: 'SUMMARY'
};

exports.JrRuleAction = exports.$Enums.JrRuleAction = {
  MATCH_ON: 'MATCH_ON',
  REJECT_ON: 'REJECT_ON',
  REPLACE: 'REPLACE'
};

exports.ReviewType = exports.$Enums.ReviewType = {
  IMPORTED: 'IMPORTED',
  DEDICATED: 'DEDICATED'
};

exports.VoteType = exports.$Enums.VoteType = {
  HELPFUL: 'HELPFUL',
  NOT_HELPFUL: 'NOT_HELPFUL'
};

exports.AddressType = exports.$Enums.AddressType = {
  SHIPPING: 'SHIPPING',
  BILLING: 'BILLING',
  BOTH: 'BOTH'
};

exports.CartStatus = exports.$Enums.CartStatus = {
  ACTIVE: 'ACTIVE',
  ABANDONED: 'ABANDONED',
  CONVERTED: 'CONVERTED',
  MERGED: 'MERGED'
};

exports.OrderStatus = exports.$Enums.OrderStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED'
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  PAID: 'PAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
  CANCELLED: 'CANCELLED'
};

exports.OrderItemStatus = exports.$Enums.OrderItemStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  FULFILLED: 'FULFILLED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
};

exports.TransactionType = exports.$Enums.TransactionType = {
  PAYMENT: 'PAYMENT',
  REFUND: 'REFUND',
  PARTIAL_REFUND: 'PARTIAL_REFUND',
  VOID: 'VOID'
};

exports.TransactionStatus = exports.$Enums.TransactionStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

exports.InventoryTransactionType = exports.$Enums.InventoryTransactionType = {
  RESTOCK: 'RESTOCK',
  SALE: 'SALE',
  RETURN: 'RETURN',
  ADJUSTMENT: 'ADJUSTMENT',
  RESERVATION: 'RESERVATION',
  RELEASE: 'RELEASE'
};

exports.RegistryType = exports.$Enums.RegistryType = {
  WISHLIST: 'WISHLIST',
  GIFT: 'GIFT',
  WEDDING: 'WEDDING',
  BABY: 'BABY',
  BIRTHDAY: 'BIRTHDAY',
  HOLIDAY: 'HOLIDAY',
  OTHER: 'OTHER'
};

exports.PurchaseStatus = exports.$Enums.PurchaseStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  RETURNED: 'RETURNED'
};

exports.RegistryUserRole = exports.$Enums.RegistryUserRole = {
  OWNER: 'OWNER',
  EDITOR: 'EDITOR',
  VIEWER: 'VIEWER'
};

exports.Prisma.ModelName = {
  User: 'User',
  Session: 'Session',
  Account: 'Account',
  Verification: 'Verification',
  Organization: 'Organization',
  Member: 'Member',
  Team: 'Team',
  TeamMember: 'TeamMember',
  Invitation: 'Invitation',
  ApiKey: 'ApiKey',
  TwoFactor: 'TwoFactor',
  BackupCode: 'BackupCode',
  Passkey: 'Passkey',
  AuditLog: 'AuditLog',
  Article: 'Article',
  Product: 'Product',
  PdpJoin: 'PdpJoin',
  PdpUrl: 'PdpUrl',
  ProductIdentifiers: 'ProductIdentifiers',
  Brand: 'Brand',
  Cast: 'Cast',
  Collection: 'Collection',
  Fandom: 'Fandom',
  Location: 'Location',
  Media: 'Media',
  ProductCategory: 'ProductCategory',
  Series: 'Series',
  Story: 'Story',
  Taxonomy: 'Taxonomy',
  JollyRoger: 'JollyRoger',
  JrExtractionRule: 'JrExtractionRule',
  JrFindReplaceReject: 'JrFindReplaceReject',
  Review: 'Review',
  FavoriteJoin: 'FavoriteJoin',
  ReviewVoteJoin: 'ReviewVoteJoin',
  Address: 'Address',
  Cart: 'Cart',
  CartItem: 'CartItem',
  Order: 'Order',
  OrderItem: 'OrderItem',
  Transaction: 'Transaction',
  Inventory: 'Inventory',
  InventoryTransaction: 'InventoryTransaction',
  Registry: 'Registry',
  RegistryItem: 'RegistryItem',
  RegistryPurchaseJoin: 'RegistryPurchaseJoin',
  RegistryUserJoin: 'RegistryUserJoin',
  WorkflowConfig: 'WorkflowConfig',
  WorkflowExecution: 'WorkflowExecution',
  WorkflowSchedule: 'WorkflowSchedule'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
