import { notFound, redirect } from 'next/navigation';

import { getRecord, updateRecord } from '../../../actions';
import { type FormField, ModelForm } from '../../../components/ModelForm';

const productFields: FormField[] = [
  {
    name: 'name',
    type: 'text',
    label: 'Product Name',
    placeholder: 'Enter product name',
    required: true,
  },
  {
    name: 'sku',
    type: 'text',
    description: 'Stock Keeping Unit for inventory tracking',
    label: 'SKU',
    placeholder: 'Enter SKU (optional)',
  },
  {
    name: 'brand',
    type: 'text',
    label: 'Brand',
    placeholder: 'Enter brand name',
  },
  {
    name: 'description',
    type: 'textarea',
    label: 'Description',
    placeholder: 'Enter product description',
    rows: 4,
  },
  {
    name: 'status',
    type: 'select',
    label: 'Status',
    options: [
      { label: 'Draft', value: 'DRAFT' },
      { label: 'Active', value: 'ACTIVE' },
      { label: 'Archived', value: 'ARCHIVED' },
      { label: 'Discontinued', value: 'DISCONTINUED' },
    ],
    required: true,
  },
  {
    name: 'price',
    type: 'number',
    description: 'Product price in selected currency',
    label: 'Price',
    min: 0,
    placeholder: '0.00',
    step: 0.01,
  },
  {
    name: 'currency',
    type: 'select',
    label: 'Currency',
    options: [
      { label: 'USD - US Dollar', value: 'USD' },
      { label: 'EUR - Euro', value: 'EUR' },
      { label: 'GBP - British Pound', value: 'GBP' },
      { label: 'CAD - Canadian Dollar', value: 'CAD' },
      { label: 'AUD - Australian Dollar', value: 'AUD' },
    ],
  },
  {
    name: 'attributes',
    type: 'json',
    description: 'Additional product attributes as JSON',
    label: 'Additional Attributes',
    placeholder: '{"color": "red", "size": "medium"}',
  },
  {
    name: 'aiGenerated',
    type: 'switch',
    description: 'Mark if this product data was generated by AI',
    label: 'AI Generated',
  },
];

interface PageProps {
  params: { id: string };
}

export default async function EditProductPage({ params }: PageProps) {
  const product = await getRecord('product', params.id);

  if (!product) {
    notFound();
  }

  // Transform product data for form
  const initialValues = {
    ...product,
    attributes: product.attributes ? JSON.stringify(product.attributes, null, 2) : '{}',
  };

  async function handleSubmit(values: Record<string, any>) {
    'use server';

    // Transform the data to match Prisma schema
    const data = {
      ...values,
      attributes: values.attributes ? JSON.parse(values.attributes) : {},
      price: values.price ? parseFloat(values.price) : null,
    };

    await updateRecord('product', params.id, data);
    redirect('/admin/products');
  }

  return (
    <ModelForm
      cancelHref="/admin/products"
      onSubmit={handleSubmit}
      fields={productFields}
      initialValues={initialValues}
      submitLabel="Update Product"
      title="Edit Product"
    />
  );
}
